### PR TITLE
Issue/merge clients

### PR DESCRIPTION
**Pull request by pmlopes**

### CODE REVIEW

**Comment by pmlopes** [comment]
I need some review here! :)

The C clients do build and work on Windows, Linux and Mac
The Python client has been updated to generate packages and the examples work
The C# also builds and works
The Node works
The Go, I've no idea

As you can see it's a huge PR so all eyes are welcome!

**Comment by vietj** [comment]
why so many commits :-) ?

**Comment by vietj** [comment]
I think we should come with a new repo for all bridge clients

**Comment by vietj** [comment]
something like vertx-eventbus-bridge-clients

**Comment by pmlopes** [comment]
There are lots of commits because I preserved the code history across all sources.

**Comment by pmlopes** [comment]
@vietj please create the new `vertx-eventbus-bridge-clients` repo and I'll move the clients there.

**Comment by vietj** [comment]
@pmlopes done https://github.com/vert-x3/vertx-eventbus-bridge-clients

**Comment by jponge** [comment]
LGTM Paulo.

The Go client works BTW (I did it)

**Comment by pmlopes** [comment]
I'll close (won't merge) this PR since the work has been moved here: 

* vert-x3/vertx-eventbus-bridge-clients#1
* vert-x3/vertx-eventbus-bridge-clients#2
* vert-x3/vertx-eventbus-bridge-clients#3
* vert-x3/vertx-eventbus-bridge-clients#4
* vert-x3/vertx-eventbus-bridge-clients#5

**Pull request closed without merging**
