### PR TITLE
TcpEventBusBridge with headers support

### PR DESCRIPTION
**Pull request by joson**
Enable message headers, forward headers to EventBus with DeliveryOptions.

### CODE REVIEW

**Comment by cescoffier** [comment]
@joson Can you give a reason why you close this ?

**Comment by joson** [comment]
I forgot to ignore none headers then it will throw a NullPointerException.
I've reopened another pull request. Please review the new one, thanks.

**Comment by cescoffier** [comment]
ok, thanks for the explanation.

**Comment by cescoffier** [comment]
PR reported as invalid by the contributor.

**Pull request closed without merging**
